name: Run Tests

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest # TODO: should probably run on all platforms, eventually. Using the bundled binary for now.

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Python for pre-commit
      uses: actions/setup-python@v3

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Lint
      run: npm run lint

    - name: Package Extension
      run: npm run package

    - name: Upload VSIX as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: npl-dev-vscode-extension
        path: "*.vsix"
